import parsingToReal from './parser';
import checkSumCalculation from './checkSum';
import writeConvertedNumbers from './resultGenerator';
import * as fs from 'fs';
// fs = require('fs');

// Reading file with the account numbers generated by the machine

// Reading the file to get details
async function readFile () {
  try {
    const response = await fs.promises.readFile('./accountNumbers.txt', 'UTF-8');
    return response;
  } catch(err) {
    console.log(err);
  }
}

async function runBankOCR() {
  const fileData = await readFile();
  if (!fileData) return;
  const parsedNumbers = await parsingToReal(fileData);
  
  if (!parsedNumbers)  return;
  const checkSumTable = await checkSumCalculation(parsedNumbers);
  
  if (!checkSumTable) return;
  writeConvertedNumbers(checkSumTable)
}

runBankOCR()

